#!/bin/bash
# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

## generate-cmake-toolchain.sh
#
# This generates a clang config file to pass default args to clang.
#
# Docs: https://clang.llvm.org/docs/UsersManual.html#configuration-files

set -e
set -x
set -o pipefail

if ! [ "$#" -ge 2 ]; then
  echo "Usage: $0 <target> <prefix_dir>"
  exit 2
fi;

## Take configuration from arguments
# This is the gcc target triple
toolchain_target="${1}"
# This is the directory where the toolchain has been installed.
toolchain_dest="${2}"

config_dest="${toolchain_dest}/bin/${toolchain_target}.cfg"

tee "${config_dest}" <<CONFIG
# Autogenerated by ${0} on $(date -u)
# Problems? Bug reporting instructions in ${toolchain_dest}/buildinfo

# Target
-target=${toolchain_target}

CONFIG
